name: fast_ui
description: A collection of Flutter packages aimed to make UI development faster
version: 0.1.2
homepage: https://github.com/Rexios80/fast_ui/tree/master/fast_ui

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fast_extensions: any
  fast_nav: any
  fast_overlays: any
  fast_rx_flutter: any
  fast_rx_persistence: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^8.0.0
