coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
    patch:
      default:
        target: auto
        threshold: 5%
        base: auto
      

flag_management:
  default_rules:
    carryforward: false
    statuses:
      - name_prefix: project-
        type: project
        target: auto
        threshold: 5%
      - name_prefix: patch-
        type: patch
        target: 90%
