// Mocks generated by Mockito 5.0.17 from annotations
// in fast_rx/testing/expect_rx.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fast_rx/src/rx_notifier.dart' as _i2;
import 'package:fast_rx/testing/expect_rx.dart' as _i5;
import 'package:flutter/foundation.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [RxNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockRxNotifier extends _i1.Mock implements _i2.RxNotifier {
  MockRxNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addStream(_i3.Stream<dynamic>? stream) =>
      super.noSuchMethod(Invocation.method(#addStream, [stream]),
          returnValueForMissingStub: null);
  @override
  T setupObserver<T>(_i2.RxObserver? observer, _i4.ValueGetter<T>? builder) =>
      (super.noSuchMethod(
          Invocation.method(#setupObserver, [observer, builder]),
          returnValue: _i5.setupObserverShim<T>(observer, builder)) as T);
}
