name: fast_extensions
description: Convenience extensions to make common Flutter tasks less annoying
version: 0.1.4
homepage: https://github.com/Rexios80/fast_ui/tree/master/fast_extensions

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^5.0.0
